packages:
  - "apps/*"
  - "libs/*"

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@scarf/scarf"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - esbuild
  - msgpackr-extract
  - nx
  - sharp
  - unrs-resolver
