import { bigint, integer, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const DOCUMENT_CATEGORIES = [
  "consent_form",
  "identification",
  "medical_certificate",
  "laboratory_report",
  "imaging",
  "referral_letter",
  "prescription",
  "clinical_attachment",
  "billing",
  "other",
] as const;
export type DocumentCategory = (typeof DOCUMENT_CATEGORIES)[number];
export type DocumentStatus = "pending_upload" | "available" | "archived";
/** Uploaded by a user, or generated by the platform (e.g. an archived laboratory report). */
export type DocumentSource = "upload" | "generated";
/** A domain that serves its documents itself (with its own visibility rules); the generic documents API leaves them alone. */
export type DocumentManager = "laboratory";

export const document = pgTable("document", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull(),
  facilityId: uuid("facility_id"),
  patientId: uuid("patient_id"),
  category: text("category").$type<DocumentCategory>().notNull(),
  title: text("title").notNull(),
  fileName: text("file_name").notNull(),
  contentType: text("content_type").notNull(),
  sizeBytes: bigint("size_bytes", { mode: "number" }).notNull(),
  storageKey: text("storage_key").notNull(),
  status: text("status").$type<DocumentStatus>().notNull().default("pending_upload"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  /** Null for documents the platform generated. */
  createdBy: uuid("created_by"),
  source: text("source").$type<DocumentSource>().notNull().default("upload"),
  uploadedAt: timestamp("uploaded_at", { withTimezone: true }),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  archivedBy: uuid("archived_by"),
  archiveReason: text("archive_reason"),
  version: integer("version").notNull().default(1),
  /** Null for ordinary documents; else the domain that alone lists and serves it (migration 0040). */
  managedBy: text("managed_by").$type<DocumentManager>(),
});

export type DocumentRecord = typeof document.$inferSelect;
