import { bigint, integer, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const DOCUMENT_CATEGORIES = [
  "consent_form",
  "identification",
  "medical_certificate",
  "laboratory_report",
  "imaging",
  "referral_letter",
  "prescription",
  "clinical_attachment",
  "billing",
  "other",
  /** A compiled copy of the patient's record, prepared for a records request. */
  "record_copy",
  "management_report",
] as const;
export type DocumentCategory = (typeof DOCUMENT_CATEGORIES)[number];
export type DocumentStatus = "pending_upload" | "available" | "archived";
/** Uploaded by a user, or generated by the platform (e.g. an archived laboratory report). */
export type DocumentSource = "upload" | "generated" | "patient_upload";
/** A domain that serves its documents itself (with its own visibility rules); the generic documents API leaves them alone. */
export type DocumentManager = "laboratory";

export const document = pgTable("document", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull(),
  facilityId: uuid("facility_id"),
  patientId: uuid("patient_id"),
  category: text("category").$type<DocumentCategory>().notNull(),
  title: text("title").notNull(),
  fileName: text("file_name").notNull(),
  contentType: text("content_type").notNull(),
  sizeBytes: bigint("size_bytes", { mode: "number" }).notNull(),
  storageKey: text("storage_key").notNull(),
  status: text("status").$type<DocumentStatus>().notNull().default("pending_upload"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  /** Null for documents the platform generated or a patient uploaded. */
  createdBy: uuid("created_by"),
  /** The MyHealth account that uploaded it (migration 0097), else null. */
  createdByPortalAccount: uuid("created_by_portal_account"),
  source: text("source").$type<DocumentSource>().notNull().default("upload"),
  uploadedAt: timestamp("uploaded_at", { withTimezone: true }),
  archivedAt: timestamp("archived_at", { withTimezone: true }),
  archivedBy: uuid("archived_by"),
  archiveReason: text("archive_reason"),
  version: integer("version").notNull().default(1),
  /** Null for ordinary documents; else the domain that alone lists and serves it (migration 0040). */
  managedBy: text("managed_by").$type<DocumentManager>(),
});

export type DocumentRecord = typeof document.$inferSelect;

/**
 * The organization's retention period per document category (0074_compliance_configuration.sql), from its own
 * retention schedule; the platform encodes none and never deletes: documents past the period are listed for review.
 */
export const documentRetentionPolicy = pgTable("document_retention_policy", {
  id: uuid("id").primaryKey().defaultRandom(),
  organizationId: uuid("organization_id").notNull(),
  category: text("category").$type<DocumentCategory>().notNull(),
  retainYears: integer("retain_years").notNull(),
  basisNote: text("basis_note").notNull(),
  status: text("status").$type<"active" | "inactive">().notNull().default("active"),
  createdBy: uuid("created_by").notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  endedBy: uuid("ended_by"),
  endedAt: timestamp("ended_at", { withTimezone: true }),
});
export type DocumentRetentionPolicyRecord = typeof documentRetentionPolicy.$inferSelect;
