export * from "./lib/duplicate-detection";
export * from "./lib/patient.dto";
export * from "./lib/patient.module";
export * from "./lib/patient.schema";
export * from "./lib/patient.views";
export * from "./lib/communication-policy";
export { normalizeContact } from "./lib/contact-normalization";
export * from "./lib/patient-record.service";
export * from "./lib/patient-registration.service";
export * from "./lib/portal/portal.schema";
export * from "./lib/portal/portal-account.service";
export * from "./lib/portal/patient-access.guard";
